baseurl = "https://gdmsl.github.io"
title = "Guido Masella"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Guido Masella"
    description = "Guido Masella's personal website"
    keywords = "blog,physicist,developer,personal"
    info = "PhD in Physics, programmer, and Linux enthusiast"
    avatarurl = "images/avatar.webp"
    #gravatar = "guido.masella@gmail.com"
    footercontent = "With magic, you can turn a frog into a prince. With science, you can turn a frog into a Ph.D and you still have the frog you started with - Terry Pratchett, Science of Discoworld"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/gdmsl/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/gdmsl/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/gdmsl/"
[[params.social]]
    name = "Group website"
    icon = "fa fa-link"
    weight = 3
    url = "https://qmtheory.fr"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

    [languages.it]
        languagename = "Italiano"

            [[languages.it.param]]
            keywords = "blog,fisico,fisica,sviluppatore,personale"
            description = "Il blog di Guido Masella"

            [[languages.it.menu.main]]
            name = "Chi sono"
            weight = 1
            url = "about/"

            [[languages.it.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

    [languages.fr]
        languagename = "Français"

            [[languages.fr.param]]
            keywords = "blog,physicien,développeur,personnel,physique"
            description = "Le blog de Guido Masella"

            [[languages.fr.menu.main]]
            name = "Qui souis-je"
            weight = 1
            url = "about/"

            [[languages.fr.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"
